/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficas;

import com.lowagie.text.Document;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import static daq.autoclave.FramePrincipal.adquirir;
import static daq.autoclave.FramePrincipal.taba2;
import daq.autoclave.Variables;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Judapies
 */
public class TablaDatos extends javax.swing.JFrame {
    /**
     * Creates new form TablaDatos
     */
    
    public TablaDatos() {
        initComponents();
        setTitle("JP Adquisicion Camara Climatica V1.0.0");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo JP2.png")).getImage());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);               
        Tabla_Resultados.setModel(Graficar.modelo2);
        Tabla_Resultados.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Resultados = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla_Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla_Resultados);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo JP2.png"))); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Exportar");
        jMenu1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PDF-icon.png"))); // NOI18N
        jMenuItem1.setText("Exportar a PDF");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Excel-icon.png"))); // NOI18N
        jMenuItem2.setText("Exportar a Excel");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Object GetData(JTable table, int row_index, int col_index){
        return table.getModel().getValueAt(row_index, col_index);
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser chooser= new JFileChooser();
        FileNameExtensionFilter filter= new FileNameExtensionFilter("Archivo PDF","pdf");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar Como");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
            
        if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            try{
            int count=Tabla_Resultados.getRowCount();
            Document document=new Document();
            String file=chooser.getSelectedFile().toString().concat(".pdf");
            PdfWriter.getInstance(document,new FileOutputStream(file));
            String str = "Adquisición de Datos Camara Climatica\nJP Bioingenieria SAS\nCiclo:"+Variables.ciclo+"\nOperador:"+Variables.operador
                        +"\nIdentificación:"+Variables.id;
                HeaderFooter header = new HeaderFooter(new Phrase(str, 
                        FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Font.NORMAL)), false);
                HeaderFooter footer = new HeaderFooter(new Phrase("www.jpinglobal.com\n"+Variables.texto, 
                        FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Font.NORMAL)), true);
                header.setAlignment(Element.ALIGN_LEFT);
                header.setBorder(Rectangle.BOX);
                document.setHeader(header);
                document.setFooter(footer);
                document.open();
            
            PdfPTable tab=new PdfPTable(Tabla_Resultados.getColumnCount());
            
            tab.addCell("Fecha");
            tab.addCell("Hora");
            tab.addCell("Temperatura");
            tab.addCell("Temperatura 2");
            tab.addCell("Humedad");
            for(int i=0;i<count;i++){
                Object obj1 = GetData(Tabla_Resultados, i, 0);
                Object obj2 = GetData(Tabla_Resultados, i, 1);
                Object obj3 = GetData(Tabla_Resultados, i, 2);
                Object obj4 = GetData(Tabla_Resultados, i, 3);                
                Object obj5 = GetData(Tabla_Resultados, i, 4);                
                
                String value1=obj1.toString();
                String value2=obj2.toString();
                String value3=obj3.toString();
                String value4=obj4.toString();
                String value5=obj5.toString();

                tab.addCell(value1);
                tab.addCell(value2);
                tab.addCell(value3);
                tab.addCell(value4);                
                tab.addCell(value5);                
            }
            document.add(tab);
            document.close();
        }
        catch(Exception e){}
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public void CargarInfo(){
        if(adquirir)
        {
            JOptionPane.showMessageDialog(null, "Detenga la adquisiciòn de datos","JP",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {   
            if(taba2.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No Hay Datos para Exportar.","JP",JOptionPane.INFORMATION_MESSAGE);
               return;
            }
            
            JFileChooser chooser= new JFileChooser();
            FileNameExtensionFilter filter= new FileNameExtensionFilter("Archivo de Excel","xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Como");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);
            
            if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
                ArrayList<JTable> tb = new ArrayList<>();
                ArrayList<String> nom = new ArrayList<>();
                tb.add(taba2);
                nom.add("Datos del Proceso");
                String file=chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Graficas.ExportarLectura e=new Graficas.ExportarLectura(new File(file), tb, nom, 1);
                    if(e.export()){
                    }
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,"Hubo un error "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                    
                }   
            }  
        }
    }
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CargarInfo();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaDatos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabla_Resultados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
