/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package daq.autoclave;

//import figuraspanel.VideoInfo;
import Graficas.Batch;
import static Graficas.Batch.TextBatch;
import Graficas.Graficar;
import Graficas.HiloGrafica;
import Graficas.TablaDatos;
import static Graficas.TablaDatos.Tabla_Resultados;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.HeaderFooter;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import comunicacion.HiloComunicacion;
import java.awt.Color;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Judapies
 */
public class FramePrincipal extends javax.swing.JFrame implements Serializable{

    public static JPopupMenu pop,popcomando;    
    private static JPanel Objeto;    
    private static JLabel jLabel4;
    JMenuItem Hojas;
    JScrollPane Rueda;
    private static FramePrincipal workspace;
    public static JLabel jl1;
    public int i=0;  //figura seleccionada
    public int width= 150;   //tama;o inicial fijo
    public int height= 150;
    public float[]dash;     // tipo linea contorno
    public int dibujar=-1;   //crea el objeto al seleccionar figura
    public static int DiaspositivaSeleccionada=1;
    public static boolean open=false;
    public static boolean imagegris=false;
    public static boolean imageguardar=false; 
    private final JScrollPane jScrollPane1;
    public static BufferedImage imagen;   
    public static boolean adquirir=false;
    
    
    public FramePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("JP Adquisicion Camara Climatica V1.0.0");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo JP2.png")).getImage());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);               
        //panelGrafica.setBackground(Color.lightGray);
        jScrollPane1 = new javax.swing.JScrollPane();                
        panelGrafica.setMaximumSize(panelGrafica.getSize());
        panelGrafica.setMinimumSize(panelGrafica.getSize());
        panelGrafica.setPreferredSize(panelGrafica.getSize());
        System.out.println(panelGrafica.getSize());
        Grafica.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Data-Line-Chart-icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panelGrafica = new javax.swing.JPanel();
        Grafica = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        taba2 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        BotonTabla = new javax.swing.JButton();
        BotonExcel = new javax.swing.JButton();
        BotonPDF = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        BotonAutomatico = new javax.swing.JButton();
        BotonPrueba = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        BotonPrueba1 = new javax.swing.JButton();
        BotonUSB = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        textTemp = new javax.swing.JMenu();
        textTemp2 = new javax.swing.JMenu();
        txtPc = new javax.swing.JMenu();
        txtPc1 = new javax.swing.JMenu();
        txtDP = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGrafica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Grafica.setVisible(true);

        taba2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(taba2);

        javax.swing.GroupLayout GraficaLayout = new javax.swing.GroupLayout(Grafica.getContentPane());
        Grafica.getContentPane().setLayout(GraficaLayout);
        GraficaLayout.setHorizontalGroup(
            GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GraficaLayout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        GraficaLayout.setVerticalGroup(
            GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraficaLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Grafica)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Grafica)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator4);

        BotonTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Database-Table-icon.png"))); // NOI18N
        BotonTabla.setMnemonic('d');
        BotonTabla.setToolTipText("Ver tabla de Datos");
        BotonTabla.setFocusable(false);
        BotonTabla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonTabla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTablaActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonTabla);

        BotonExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Excel-icon.png"))); // NOI18N
        BotonExcel.setMnemonic('e');
        BotonExcel.setToolTipText("Exportar a Excel");
        BotonExcel.setFocusable(false);
        BotonExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExcelActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonExcel);

        BotonPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PDF-icon.png"))); // NOI18N
        BotonPDF.setMnemonic('p');
        BotonPDF.setToolTipText("Exportar a PDF");
        BotonPDF.setFocusable(false);
        BotonPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPDFActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonPDF);
        jToolBar1.add(jSeparator9);

        BotonAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Button-Play-icon.png"))); // NOI18N
        BotonAutomatico.setMnemonic('S');
        BotonAutomatico.setToolTipText("Iniciar/Detener Adquisición");
        BotonAutomatico.setFocusable(false);
        BotonAutomatico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonAutomatico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAutomaticoActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonAutomatico);

        BotonPrueba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stopwatch-start-icon.png"))); // NOI18N
        BotonPrueba.setMnemonic('t');
        BotonPrueba.setToolTipText("Tiempo de muestreo");
        BotonPrueba.setFocusable(false);
        BotonPrueba.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonPrueba.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPruebaActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonPrueba);
        jToolBar1.add(jSeparator10);

        BotonPrueba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/information-icon.png"))); // NOI18N
        BotonPrueba1.setMnemonic('t');
        BotonPrueba1.setToolTipText("Información");
        BotonPrueba1.setFocusable(false);
        BotonPrueba1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonPrueba1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonPrueba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrueba1ActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonPrueba1);

        BotonUSB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/USB-Rojo.png"))); // NOI18N
        BotonUSB.setMnemonic('t');
        BotonUSB.setToolTipText("Conexión USB");
        BotonUSB.setFocusable(false);
        BotonUSB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonUSB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonUSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUSBActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonUSB);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo JP3.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        textTemp.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jMenuBar1.add(textTemp);

        textTemp2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jMenuBar1.add(textTemp2);

        txtPc.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jMenuBar1.add(txtPc);

        txtPc1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jMenuBar1.add(txtPc1);

        txtDP.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jMenuBar1.add(txtDP);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void BotonTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTablaActionPerformed
        try {
            TablaDatos tb = new TablaDatos();
            tb.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ""+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonTablaActionPerformed

    public void CargarInfo(){
        if(adquirir)
        {
            JOptionPane.showMessageDialog(null, "Detenga la adquisiciòn de datos","JP",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {   
            if(taba2.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No Hay Datos para Exportar.","JP",JOptionPane.INFORMATION_MESSAGE);
               return;
            }
            
            JFileChooser chooser= new JFileChooser();
            FileNameExtensionFilter filter= new FileNameExtensionFilter("Archivo de Excel","xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Como");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);
            
            if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
                ArrayList<JTable> tb = new ArrayList<>();
                ArrayList<String> nom = new ArrayList<>();
                tb.add(taba2);
                nom.add("Datos del Proceso");
                String file=chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Graficas.ExportarLectura e=new Graficas.ExportarLectura(new File(file), tb, nom, 1);
                    if(e.export()){
                    }
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,"Hubo un error "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                    
                }   
            }  
        }
    }
    
    private void BotonExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExcelActionPerformed
        CargarInfo();
    }//GEN-LAST:event_BotonExcelActionPerformed

    private void BotonAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAutomaticoActionPerformed
        if(!adquirir){
            if(!Variables.cargoData){
                int continuar = JOptionPane.showConfirmDialog(this,"Va a iniciar una nueva adquisición"
                                                                + "\n¿Desea modificar la información del ciclo?");
                if(continuar == JOptionPane.YES_OPTION){//si se selecciona SI 
                    Batch b=new Batch();
                    b.setVisible(true);
                    dispose();
                }
                else{
                    int continuar2 = JOptionPane.showConfirmDialog(this,"Va a iniciar una nueva adquisición, esto borrara los datos previos"
                                                                + "\n¿Desea continuar?");
                    if(continuar2 == JOptionPane.YES_OPTION){//si se selecciona SI 
                        HiloGrafica.estadoAdquisicion=true;
                        new Thread(new HiloGrafica()).start();
                        adquirir=true;
                        BotonAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Button-Stop-icon.png")));
                    }
                }
            }else{
                HiloGrafica.estadoAdquisicion=true;
                new Thread(new HiloGrafica()).start();
                adquirir=true;
                BotonAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Button-Stop-icon.png")));
            }
        }else{
            HiloGrafica.estadoAdquisicion=false;
            adquirir=false;
            BotonAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Button-Play-icon.png")));
            Variables.cargoData=false;
        }
    }//GEN-LAST:event_BotonAutomaticoActionPerformed

    private void BotonPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPruebaActionPerformed
        if(!adquirir){
            try {
                Variables.Tmuestreo = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el tiempo de muestreo deseado en ms",Variables.Tmuestreo));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, ""+e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Detenga la adquisición de datos","JP",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BotonPruebaActionPerformed

    public Object GetData(JTable table, int row_index, int col_index){
        return table.getModel().getValueAt(row_index, col_index);
    }
    
    private void BotonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPDFActionPerformed
        if(adquirir)
        {
            JOptionPane.showMessageDialog(null, "Detenga la adquisiciòn de datos","JP",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        { 
            JTable tablas = new JTable(null);
            tablas.setModel(Graficar.modelo2);
            JFileChooser chooser= new JFileChooser();
            FileNameExtensionFilter filter= new FileNameExtensionFilter("Archivo PDF","pdf");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Como");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);
            
            if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
                try{
            int count=tablas.getRowCount();
                Document document=new Document();
                    String file=chooser.getSelectedFile().toString().concat(".pdf");
                PdfWriter.getInstance(document,new FileOutputStream(file));
                String str = "Adquisición de Datos Camara Climatica\nJP Bioingenieria SAS\nCiclo:"+Variables.ciclo+"\nOperador:"+Variables.operador
                        +"\nIdentificación:"+Variables.id;
                HeaderFooter header = new HeaderFooter(new Phrase(str, 
                        FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Font.NORMAL)), false);
                HeaderFooter footer = new HeaderFooter(new Phrase("www.jpinglobal.com\n"+Variables.texto, 
                        FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Font.NORMAL)), true);
                header.setAlignment(Element.ALIGN_LEFT);
                header.setBorder(Rectangle.BOX);
                document.setHeader(header);
                document.setFooter(footer);
                document.open();
                
                PdfPTable tab=new PdfPTable(tablas.getColumnCount());
                
                tab.addCell("Fecha");
                tab.addCell("Hora");
                tab.addCell("Temperatura");
                tab.addCell("Temperatura 2");
                tab.addCell("Humedad");
                for(int i=0;i<count;i++){
                    Object obj1 = GetData(tablas, i, 0);
                    Object obj2 = GetData(tablas, i, 1);
                    Object obj3 = GetData(tablas, i, 2);
                    Object obj4 = GetData(tablas, i, 3);
                    Object obj5 = GetData(tablas, i, 4);
                
                    String value1=obj1.toString();
                    String value2=obj2.toString();
                    String value3=obj3.toString();
                    String value4=obj4.toString();
                    String value5=obj5.toString();

                    tab.addCell(value1);
                    tab.addCell(value2);
                    tab.addCell(value3);
                    tab.addCell(value4);                        
                    tab.addCell(value5);                        
                }
               document.add(tab);
                document.close();
            }
            catch(Exception e){}
            }
        }
    }//GEN-LAST:event_BotonPDFActionPerformed

    private void BotonPrueba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrueba1ActionPerformed
        JOptionPane.showMessageDialog(this," JP Software Adquisicion Camara Climatica V1.0.0"+"\n 2022\nCopyright JP Bioingenieria SAS\n @judapies","Información",JOptionPane.INFORMATION_MESSAGE);     
    }//GEN-LAST:event_BotonPrueba1ActionPerformed

    private void BotonUSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonUSBActionPerformed
                                          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
        try {
		UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
	}
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FramePrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        //new Thread(new HiloComunicacion()).start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAutomatico;
    private javax.swing.JButton BotonExcel;
    private javax.swing.JButton BotonPDF;
    private javax.swing.JButton BotonPrueba;
    private javax.swing.JButton BotonPrueba1;
    private javax.swing.JButton BotonTabla;
    public static javax.swing.JButton BotonUSB;
    public static javax.swing.JInternalFrame Grafica;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JPanel panelGrafica;
    public static javax.swing.JTable taba2;
    public static javax.swing.JMenu textTemp;
    public static javax.swing.JMenu textTemp2;
    public static javax.swing.JMenu txtDP;
    public static javax.swing.JMenu txtPc;
    public static javax.swing.JMenu txtPc1;
    // End of variables declaration//GEN-END:variables
}